
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-11-19T17:30:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0a161befb2235ef37c63d1042d1f9d500d1e944b",
 "version": "1.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
