
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-12-11T02:56:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "31bdf475f3189022f01d4aab613cd4cc0dacadd5",
 "version": "1.9.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
