# This file was auto-generated by Fern from our API Definition.

import typing

ChatStreamEndEventY8Gq2XFinishReason = typing.Union[
    typing.Literal["COMPLETE", "ERROR_LIMIT", "MAX_TOKENS", "ERROR", "ERROR_TOXIC"], typing.Any
]
