# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class PromptResponseV2(UncheckedBaseModel):
    """
    Response from the v2 prompt endpoint — the constructed text prompt without generation.
    """

    prompt: str = pydantic.Field()
    """
    The constructed text prompt that would be sent to the model for this chat request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow")  # type: ignore # Pydantic v2
    else:

        class Config:
            smart_union = True
            extra = pydantic.Extra.allow
